import { describe, it, expect } from 'vitest';

import * as indexModule from './index.ts';

describe('index', () => {
  it('has the expected exports', () => {
    expect(Object.keys(indexModule).sort()).toStrictEqual([
      'CapDataStruct',
      'DEFAULT_BASE_DELAY_MS',
      'DEFAULT_MAX_DELAY_MS',
      'DEFAULT_MAX_RETRY_ATTEMPTS',
      'EmptyJsonArray',
      'GET_DESCRIPTION',
      'abortableDelay',
      'calculateReconnectionBackoff',
      'callable',
      'collectSheafGuard',
      'constant',
      'delay',
      'fallthrough',
      'fetchValidatedJson',
      'fromHex',
      'getStalk',
      'guardCoversPoint',
      'ifDefined',
      'installWakeDetector',
      'isCapData',
      'isJsonRpcCall',
      'isJsonRpcMessage',
      'isPrimitive',
      'isTypedArray',
      'isTypedObject',
      'isVatBundle',
      'jsonSchemaToStruct',
      'makeCounter',
      'makeDefaultExo',
      'makeDefaultInterface',
      'makeDiscoverableExo',
      'makeRemoteSection',
      'mergeDisjointRecords',
      'methodArgsToStruct',
      'noopLift',
      'prettifySmallcaps',
      'proxyLift',
      'retry',
      'retryWithBackoff',
      'sheafify',
      'source',
      'stringify',
      'toHex',
      'waitUntilQuiescent',
      'withFilter',
      'withRanking',
    ]);
  });
});
