---
ignores:
  # monorepo
  - '@ocap/cli'

  # eslint and prettier
  - '@*/eslint-*'
  - '@typescript-eslint/*'
  - 'eslint'
  - 'eslint-*'
  - 'prettier-plugin-*'
  - 'typescript-eslint'

  # @ts-bridge
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'

  # vitest
  - 'vite'
  - '@types/vitest'
  - '@vitest/coverage-istanbul'
  - 'playwright'
  - 'vitest'
  - 'vitest-fetch-mock'
  # we explicitly require cookie ^0.7.0 to eliminate a security vulnerability
  # https://github.com/advisories/GHSA-pxg6-pf52-xh8x
  - 'cookie'

  # miscellaneous
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@types/chrome'
  - '@types/lodash'
  - 'rimraf'
  - 'simple-git-hooks'
  - 'typedoc'
  - 'typescript'
  - 'typescript-plugin-css-modules'

  # Used by @ocap/nodejs to build the sqlite3 bindings
  - 'node-gyp'

  # These are peer dependencies of various modules we actually do
  # depend on, which have been elevated to full dependencies (even
  # though we don't actually depend on them) in order to work around a
  # bug in the bundler wherein it gets confused by absent peer
  # dependencies.  These should be removed (both from here and from
  # the declared dependencies in package.json) once KK fixes the
  # bundler, which should be RSN.
  - '@metamask/approval-controller'
  - 'ava'
  - 'webextension-polyfill'
  - '@types/webextension-polyfill'
