---
ignores:
  # eslint and prettier
  - '@*/eslint-*'
  - '@typescript-eslint/*'
  - 'eslint'
  - 'eslint-*'
  - 'prettier-plugin-*'
  - 'typescript-eslint'

  # @ts-bridge
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'

  # vitest
  - '@types/vitest'
  - '@vitest/coverage-v8'
  - 'vitest'

  # miscellaneous
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@types/chrome'
  - '@types/lodash'
  - 'rimraf'
  - 'simple-git-hooks'
  - 'typedoc'
  - 'typescript'
