---
ignores:
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'
  - '@yarnpkg/types'
  - 'prettier-plugin-packagejson'
  - 'rimraf'
  - 'typedoc'
  - '@types/lodash'
