---
ignores:
  # eslint and prettier
  - '@*/eslint-*'
  - '@typescript-eslint/*'
  - 'eslint'
  - 'eslint-*'
  - 'prettier-plugin-*'
  - 'typescript-eslint'

  # @ts-bridge
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'

  # vitest
  - 'vite'
  - '@types/vitest'
  - '@vitest/coverage-istanbul'
  - 'playwright'
  - 'vitest'
  # we explicitly require cookie ^0.7.0 to eliminate a security vulnerability
  # https://github.com/advisories/GHSA-pxg6-pf52-xh8x
  - 'cookie'

  # miscellaneous
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@types/chrome'
  - '@types/lodash'
  - 'rimraf'
  - 'simple-git-hooks'
  - 'typedoc'
  - 'typescript'
