---
ignores:
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'
  - '@types/node'
  - '@yarnpkg/*'
  - 'jsdom'
  - 'prettier-plugin-*'
  - 'typedoc'
  - 'vite-tsconfig-paths'
  - 'vite'
  - 'vitest'
