---
ignores:
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'
  - '@types/chrome'
  - '@types/lodash'
  - '@vitest/coverage-v8'
  - 'depcheck' # ._.
  - 'prettier-plugin-packagejson'
  - 'rimraf'
  - 'simple-git-hooks'
  - 'typedoc'
