---
ignores:
  - '@arethetypeswrong/cli'
  - '@lavamoat/allow-scripts'
  - '@lavamoat/preinstall-always-fail'
  - '@metamask/auto-changelog'
  - '@ts-bridge/cli'
  - '@ts-bridge/shims'
  - '@vitest/coverage-v8'
  - 'depcheck' # ._.
  - 'prettier-plugin-packagejson'
  - 'rimraf'
  - 'typedoc'
  - '@types/lodash'

ignore-patterns:
  - /types.d.ts
