/**
 * Master markdown for the logistics-fulfillment service.
 *
 * The same operator handles two distinct kinds of engagement, so the
 * template ships two variants. `MASTER_MD_PRODUCTION` is the full
 * storefront-fulfillment plan: marketplace webhook integration,
 * returns flow, per-unit storage rates, etc. `MASTER_MD_TRIAL` is
 * the small-batch trial-distribution variant: hand-pack a known list
 * of beta units, ship by curated address list, no marketplace
 * integration. The service-side template renderer picks one based on
 * the brief.
 *
 * Token catalog (production variant):
 *   {{providerLabel}}       provider identifier
 *   {{warehouseRegion}}     warehouse location ("West Coast", etc.)
 *   {{warehouseCity}}       warehouse city ("Sparks, NV", etc.)
 *   {{storagePerUnit}}      monthly storage cost per unit ("$0.45", etc.)
 *   {{pickPackPerOrder}}    pick-and-pack labor per order ("$2.10", etc.)
 *   {{insertCost}}          packaging insert cost per order ("$0.35", etc.)
 *   {{groundZone1to4}}      domestic ground rate, zones 1-4 ("$6.80", etc.)
 *   {{groundZone5to8}}      domestic ground rate, zones 5-8 ("$8.40", etc.)
 *   {{intlRate}}            international rate ("$24.00", etc.)
 *   {{returnRate}}          per-return handling fee ("$3.90", etc.)
 *   {{firstMonthFloor}}     minimum monthly invoice ("$95", etc.)
 *   {{cutOffTime}}          daily cut-off for same-day pick
 *                           ("2 PM local", "3 PM local", etc.)
 *   {{leadDays}}            integration lead time
 *                           ("3 business days", etc.)
 *
 * Token catalog (trial variant):
 *   {{providerLabel}}       provider identifier
 *   {{warehouseRegion}}     warehouse location
 *   {{warehouseCity}}       warehouse city
 *   {{unitCount}}           trial batch size ("15 units", etc.)
 *   {{trialPackLabor}}      one-time hand-pack labor ("$120", etc.)
 *   {{trialShipFlat}}       per-shipment ground rate ("$8.80", etc.)
 *   {{trialLeadDays}}       turnaround for the trial run
 *                           ("2 business days", etc.)
 */
export const MASTER_MD_PRODUCTION = `# Fulfillment plan — LAUR

## Operator

**Provider:** {{providerLabel}}
**Warehouse of record:** {{warehouseCity}} ({{warehouseRegion}})
**Integration lead time:** {{leadDays}} from signed agreement

## Receiving and storage

- Receive units in pallet lots from the manufacturer of record, QA-
  count against the bill of lading, and place on contracted racking.
- Monthly storage: {{storagePerUnit}} per unit, billed against
  actual on-hand inventory at month-end.
- Minimum monthly invoice (floor): {{firstMonthFloor}} — applies
  during early ramp before unit volume exceeds the floor.

## Per-order pick, pack, and ship

- Pick-and-pack labor: {{pickPackPerOrder}} per order, includes one
  inner box plus the marketing insert.
- Custom inserts and accessory pouches: {{insertCost}} per order.
- Shipping rates (negotiated carrier accounts, billed at cost +
  handling):
  - Domestic ground, zones 1-4: {{groundZone1to4}}
  - Domestic ground, zones 5-8: {{groundZone5to8}}
  - International (DDU, customer pays duties): {{intlRate}}
- Same-day pick cut-off: {{cutOffTime}}. Orders placed after the
  cut-off ship the following business day.

## Returns

- Pre-paid return label generated by the storefront platform.
- Inspect, restock if sellable, scrap if not. Damage notes attach
  to the customer record.
- Per-return processing fee: {{returnRate}} (label + inspection +
  inventory adjustment).

## Marketplace integration

- Webhook listener for incoming orders from the storefront
  platform (Shopify, marketplace-direct, BigCommerce, custom).
- Status callbacks for picked / packed / shipped / delivered /
  returned, mapped to the storefront's expected event names.
- Inventory level sync every 15 minutes to prevent oversell.

## Hand-off check

- First inbound pallet test: a small sub-pallet (10-20 units) is
  shipped to the warehouse and round-tripped through the picking
  workflow before the storefront accepts orders, to validate
  packaging, labeling, and weight class.
- After hand-off check passes, the storefront listing flips live.
`;

export const MASTER_MD_TRIAL = `# Trial distribution plan — LAUR

## Operator

**Provider:** {{providerLabel}}
**Warehouse of record:** {{warehouseCity}} ({{warehouseRegion}})
**Turnaround:** {{trialLeadDays}} from inbound receipt

## Receive and stage

- Accept the inbound shipment from the manufacturer of record (about
  {{unitCount}}).
- QA-count against the bill of lading, set aside on a single
  staging pallet — no long-term storage racking; this is a one-shot
  distribution.

## Pack and address

- Hand-pack each unit: device + a one-page beta welcome card +
  return shipping label (pre-paid) tucked inside the box.
- One-time hand-pack labor for the batch: {{trialPackLabor}},
  including label preparation.
- Address list is supplied by the inventor (or producer) as a CSV.
  We do not source the recipient list ourselves.

## Ship

- Domestic ground, one shipment per recipient: {{trialShipFlat}}
  flat (handling included).
- International recipients quoted ad-hoc if any; not assumed in this
  estimate.
- Tracking numbers exported back to the inventor once labels print.

## What is _not_ in this plan

- No marketplace integration (Shopify, marketplace-direct,
  BigCommerce). This is a one-shot push to a curated list; no
  inbound order webhook is wired.
- No inventory-level sync; the operator's view of stock ends when
  the last trial unit ships.
- No ongoing returns flow. The pre-paid return label in each box
  is for the trial period only and routes back to the inventor, not
  to ongoing restocking.

When the program graduates to general retail, we'll re-engage on
the full storefront-fulfillment plan — same operator, separate
contract.
`;
