/**
 * A role in a chat conversation.
 */
export type ChatRole = 'system' | 'user' | 'assistant' | 'tool';

/**
 * A single tool call made by the model.
 */
export type ToolCall = {
  id: string;
  type: 'function';
  index?: number;
  function: { name: string; arguments: string };
};

/**
 * A tool definition passed to the model.
 */
export type Tool = {
  type: 'function';
  function: {
    name: string;
    description?: string;
    parameters?: {
      type: 'object';
      properties?: Record<string, unknown>;
      required?: string[];
    };
  };
};

/**
 * A single message in a chat conversation.
 */
export type ChatMessage = {
  role: ChatRole;
  content: string;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
};

/**
 * Token usage statistics for a completion request.
 */
export type Usage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};

/**
 * Options shared by raw sampling requests.
 */
export type SampleOptions = {
  temperature?: number;
  top_p?: number;
  seed?: number;
  max_tokens?: number;
  stop?: string | string[];
};

/**
 * Parameters for a raw token-prediction request (bypasses chat template).
 */
export type SampleParams = {
  model: string;
  prompt: string;
} & SampleOptions;

/**
 * Result of a raw token-prediction request.
 */
export type SampleResult = {
  text: string;
};

/**
 * Parameters for a chat completion request.
 */
export type ChatParams = {
  model: string;
  messages: ChatMessage[];
  tools?: Tool[];
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  stop?: string | string[];
  seed?: number;
  n?: number;
  /** When `true`, the response is an SSE stream of {@link ChatStreamChunk}s. */
  stream?: boolean;
};

/**
 * A partial message delta from a streaming chat completion response.
 */
export type ChatStreamDelta = {
  role?: ChatRole;
  content?: string;
};

/**
 * A single chunk from a streaming chat completion response.
 */
export type ChatStreamChunk = {
  id: string;
  model: string;
  choices: {
    delta: ChatStreamDelta;
    index: number;
    finish_reason: string | null;
  }[];
};

/**
 * A single choice in a chat completion response.
 */
export type ChatChoice = {
  message: ChatMessage;
  index: number;
  finish_reason: string | null;
};

/**
 * Result of a chat completion request.
 */
export type ChatResult = {
  id: string;
  model: string;
  choices: ChatChoice[];
  usage: Usage;
};

/**
 * Minimal service interface required by `makeChatClient`.
 */
export type ChatService = {
  chat: (params: ChatParams) => Promise<ChatResult>;
};

/**
 * Minimal service interface required by `makeSampleClient`.
 */
export type SampleService = {
  sample: (params: SampleParams) => Promise<SampleResult>;
};

/**
 * Configuration information for a language model.
 * Contains the model identifier and optional configuration parameters.
 *
 * @template Options - The type of options supported by the model
 */
export type ModelInfo<Options = unknown> = {
  model: string;
  options?: Partial<Options>;
};

/**
 * Interface for a language model that can be loaded, unloaded, and used for text generation.
 * Provides a standardized interface for interacting with different language model implementations.
 *
 * @template Options - The type of options supported by the model
 * @template Response - The type of response generated by the model
 */
export type LanguageModel<Options, Response> = {
  /**
   * Retrieves information about the model configuration.
   *
   * @returns A promise that resolves to the model information
   */
  getInfo: () => Promise<ModelInfo<Options>>;

  /**
   * Loads the model into memory and keeps it alive indefinitely.
   *
   * @returns A promise that resolves when the model is loaded.
   */
  load: () => Promise<void>;
  /**
   * Unloads the model from memory.
   *
   * @returns A promise that resolves when the model is unloaded.
   */
  unload: () => Promise<void>;
  /**
   * Generates a response from the model based on the provided prompt.
   *
   * @param prompt - The prompt to complete.
   * @param options - The options to pass to the model.
   * @returns A promise that resolves to an async iterable of response chunks, or rejects if an error occurs.
   */
  sample: (
    prompt: string,
    options?: Partial<Options>,
  ) => Promise<{
    stream: AsyncIterable<Response>;
    abort: () => Promise<void>;
  }>;
};

/**
 * Configuration for creating a language model instance.
 * Specifies which model to use and any model-specific options.
 *
 * @template Options - The type of options supported by the model
 */
export type InstanceConfig<Options> = {
  model: string;
  options?: Partial<Options>;
};

/**
 * Service interface for creating language model instances.
 * Provides a factory pattern for instantiating language models with specific configurations.
 *
 * @template Config - The type of configuration accepted by the service
 * @template Options - The type of options supported by created models
 * @template Response - The type of response generated by created models
 */
export type LanguageModelService<Config, Options, Response> = {
  /**
   * Creates a new language model instance with the specified configuration.
   *
   * @param config - The configuration for the model instance
   * @returns A promise that resolves to a language model instance
   */
  makeInstance: (
    config: InstanceConfig<Config>,
  ) => Promise<LanguageModel<Options, Response>>;
};
