/**
 * Contact-point and contact-initiation interfaces.
 *
 * Contact points are remotable objects, not JSON-serializable data, so they
 * are typed in TypeScript but not validated at the wire level.
 */

import { array, exactOptional, object, string } from '@metamask/superstruct';
import type { Infer, Struct } from '@metamask/superstruct';

import { ServiceDescriptionStruct } from './service-description.ts';
import type { ServiceDescription } from './service-description.ts';

/**
 * The service API as seen by the consumer: the concrete method interface
 * through which service requests are made. The actual shape is
 * service-specific and is fully described by `ServiceDescription.apiSpec`.
 * This type serves as a nominal bound for typed references.
 */
export type ServicePoint = {
  [method: string]: (...args: unknown[]) => Promise<unknown>;
};

/**
 * An authentication/authorization credential. Shape is access-model
 * specific, so it is left as `unknown` at this layer.
 */
export type Credential = unknown;

/**
 * Endpoint for submitting credentials in a permissioned contact flow. On
 * success, returns a usable service endpoint.
 */
export type CredentialSubmissionPoint = {
  submit(credential: Credential): Promise<ServicePoint>;
};

/**
 * Permissioned access-model response: a credential spec plus an ocap to
 * submit credentials to. On successful submission the consumer receives a
 * service endpoint.
 */
export type PermissionedContactResponse = {
  credentialSpec: string;
  credentialSubmissionPoint: CredentialSubmissionPoint;
};

/**
 * Description of a required code-bundle certification.
 */
export type CertificationRequirement = {
  description?: string;
  acceptedCertificationKinds: string[];
};

export const CertificationRequirementStruct: Struct<CertificationRequirement> =
  object({
    description: exactOptional(string()),
    acceptedCertificationKinds: array(string()),
  });

/**
 * A serializable bundle of code suitable for loading into a vat.
 */
export type VatCodeBundle = {
  payload: unknown;
};

/**
 * A certificate attesting to some property of a code bundle, issued by a
 * body whose judgment the provider trusts.
 */
export type ValidationCertificate = {
  issuer: string;
  attestations: string[];
  signature: string;
};

export const ValidationCertificateStruct: Struct<ValidationCertificate> =
  object({
    issuer: string(),
    attestations: array(string()),
    signature: string(),
  });

/**
 * Endpoint for submitting a validated-client code bundle. The provider
 * performs whatever verification it desires (certificate checks, static
 * analysis, human review, etc.) and, on success, launches a vat containing
 * the bundle endowed with the service endpoint. Returns a reference to the
 * vat root or a designated ocap within it.
 */
export type CodeSubmissionPoint = {
  submit(
    bundle: VatCodeBundle,
    certificates?: ValidationCertificate[],
  ): Promise<unknown>;
};

/**
 * Validated-client access-model response: the required certifications and an
 * ocap for submitting a code bundle.
 */
export type ValidatedClientContactResponse = {
  requiredCertifications: CertificationRequirement[];
  codeSubmissionPoint: CodeSubmissionPoint;
};

/**
 * Public access-model response: the provider returns a service endpoint
 * directly.
 */
export type PublicContactResponse = ServicePoint;

/**
 * The response returned by `ContactPoint.initiateContact()`. The variant
 * returned depends on the service's access model.
 */
export type ContactResponse =
  | PublicContactResponse
  | PermissionedContactResponse
  | ValidatedClientContactResponse;

/**
 * The contact protocol: the uniform interface implemented by every contact
 * endpoint, regardless of the underlying service.
 */
export type ContactPoint = {
  /** Obtain the service description for this service. */
  getServiceDescription(): Promise<ServiceDescription>;

  /**
   * Callback for the service matcher to validate that the registration of
   * this service was legitimate. The matcher supplies the token it received
   * in the `register*` call; the provider verifies the token matches a
   * token it previously issued.
   */
  confirmServiceRegistration(registrationToken: string): Promise<void>;

  /**
   * Initiate contact with the service. The shape of the response depends on
   * the service's access model (see {@link ContactResponse}).
   */
  initiateContact(): Promise<ContactResponse>;
};

/**
 * A registration token generated by the provider and exchanged with the
 * matcher. Its value is opaque to the matcher; the provider uses it to
 * authenticate the callback from the matcher during
 * `confirmServiceRegistration`.
 */
export const RegistrationTokenStruct: Struct<string> = string();

export type RegistrationToken = Infer<typeof RegistrationTokenStruct>;

/**
 * Shape used when a provider registers a service directly by value
 * (not via URL or ocap reference).
 */
export const RegistrationEnvelopeStruct = object({
  description: ServiceDescriptionStruct,
  registrationToken: RegistrationTokenStruct,
});

export type RegistrationEnvelope = Infer<typeof RegistrationEnvelopeStruct>;
