import { ErrorCode } from '../error-codes.ts';

/**
 * Error options with optional stack trace.
 */
type ErrorOptionsWithStack = {
  cause?: Error;
  stack?: string;
};

/**
 * Bundleable version of SampleGenerationError.
 * This version does not include marshaling logic to avoid dependencies
 * on @metamask/utils that prevent vat bundling.
 *
 * An error indicating that the LLM generated invalid response.
 * This error should trigger resampling from the LLM.
 */
export class SampleGenerationError extends Error {
  public readonly code: typeof ErrorCode.SampleGenerationError;

  public readonly data: { sample: string };

  /**
   * Creates a new SampleGenerationError.
   *
   * @param sample - The invalid sample text generated by the LLM.
   * @param cause - The underlying error that caused sample generation to fail.
   * @param options - Additional error options including stack.
   * @param options.stack - The stack trace of the error.
   */
  constructor(sample: string, cause: Error, options?: ErrorOptionsWithStack) {
    super('LLM generated invalid response.', { cause });

    this.name = 'SampleGenerationError';
    this.code = ErrorCode.SampleGenerationError;
    this.data = { sample };

    if (options?.stack) {
      this.stack = options.stack;
    }

    harden(this);
  }
}
harden(SampleGenerationError);
