name: Dependabot Dedupe

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-dedupe:
    runs-on: ubuntu-latest
    # Run this job only if it's Dependabot creating or updating the PR
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Run yarn dedupe
        run: |
          yarn dedupe
          git add yarn.lock
          if git diff --staged --quiet; then
            echo "No deduplication needed"
          else
            git commit -m "chore: dedupe yarn.lock"
            git push
          fi
