name: Publish to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        description:
          'Subdirectory of the site to publish into; the deployment replaces the
          entire site'
        required: true
        type: string
      artifact_name:
        description: 'Name of artifact to download'
        required: true
        type: string

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact_name }}
          path: _site/${{ inputs.destination_dir }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
